In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df=pd.read_csv('waveform_data.csv', header=None)
df

0     1     2     3     4     5     6     7     8     9   ...    12  \
0    -1.23 -1.56 -1.75 -0.28  0.60  2.22  0.85  0.21 -0.20  0.89  ...  2.89   
1    -0.69  2.43  0.61  2.08  2.30  3.25  5.52  4.55  2.97  2.22  ...  1.24   
2    -0.12 -0.94  1.29  2.59  2.42  3.55  4.94  3.25  1.90  2.07  ...  2.50   
3     0.86  0.29  2.19 -0.02  1.13  2.51  2.37  5.45  5.45  4.84  ...  2.58   
4     1.16  0.37  0.40 -0.59  2.66  1.00  2.69  4.06  5.34  3.53  ...  4.30   
...    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
4995 -0.65  0.69  2.29 -0.16  0.51  0.26  2.34 -0.42  0.49  0.31  ...  3.46   
4996 -0.02  0.67  2.34  3.18  2.16  4.77  6.70  4.54  4.92  3.39  ...  1.53   
4997  0.01 -1.99  0.16  2.30 -0.53  1.93  3.61  3.00  4.61  5.73  ...  3.14   
4998 -0.40  0.41 -0.48  1.04  0.79 -0.66  1.18  0.52  2.20  0.59  ...  3.64   
4999  0.63 -0.07  2.71  2.55  3.36  3.22  3.69  4.67  3.45  3.87  ... -0.52   

        13    14    15    16    17    18    19    20  21  
0     7.75  4.59  3.15  5.12  3.32  1.20  0.24 -0.56   2  
1     1.89  1.88 -1.34  0.83  1.41  1.78  0.60  2.42   1  
2     0.12  1.41  2.78  0.64  0.62 -0.01 -0.79 -0.12   0  
3     1.40  1.24  1.41  1.07 -1.43  2.84 -1.18  1.12   1  
4     1.84  1.73  0.21 -0.18  0.13 -0.21 -0.80 -0.68   1  
...    ...   ...   ...   ...   ...   ...   ...   ...  ..  
4995  4.81  5.49  5.19  3.10  3.86  2.96  1.09 -1.42   0  
4996  2.52  1.14 -1.56 -1.18 -0.56  0.02 -1.05 -0.18   1  
4997  3.04  1.61  0.60 -0.52  0.62  1.00  1.21 -0.27   1  
4998  3.62  5.97  2.63  3.83  1.72  2.08  1.31  1.37   0  
4999  1.90  0.88  3.15  1.27 -0.53  0.09  0.01  0.60   1  

[5000 rows x 22 columns]

In [ ]:
df.isnull().sum()

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
19    0
20    0
21    0
dtype: int64

In [ ]:
df.columns

Int64Index([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
            19, 20, 21],
           dtype='int64')

In [ ]:
x=df.drop(21,axis=1)
y=df[21]

In [ ]:
print(x)
print(y)
x.describe()

        0     1     2     3     4     5     6     7     8     9   ...    11  \
0    -1.23 -1.56 -1.75 -0.28  0.60  2.22  0.85  0.21 -0.20  0.89  ...  4.20   
1    -0.69  2.43  0.61  2.08  2.30  3.25  5.52  4.55  2.97  2.22  ...  1.61   
2    -0.12 -0.94  1.29  2.59  2.42  3.55  4.94  3.25  1.90  2.07  ...  1.45   
3     0.86  0.29  2.19 -0.02  1.13  2.51  2.37  5.45  5.45  4.84  ...  4.05   
4     1.16  0.37  0.40 -0.59  2.66  1.00  2.69  4.06  5.34  3.53  ...  4.79   
...    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
4995 -0.65  0.69  2.29 -0.16  0.51  0.26  2.34 -0.42  0.49  0.31  ...  4.54   
4996 -0.02  0.67  2.34  3.18  2.16  4.77  6.70  4.54  4.92  3.39  ...  1.50   
4997  0.01 -1.99  0.16  2.30 -0.53  1.93  3.61  3.00  4.61  5.73  ...  4.25   
4998 -0.40  0.41 -0.48  1.04  0.79 -0.66  1.18  0.52  2.20  0.59  ...  4.85   
4999  0.63 -0.07  2.71  2.55  3.36  3.22  3.69  4.67  3.45  3.87  ...  1.46   

        12    13    14    15    16    17    18    1

0            1            2            3            4   \
count  5000.000000  5000.000000  5000.000000  5000.000000  5000.000000   
mean      0.005144     0.338746     0.672438     0.991610     1.310888   
std       1.010130     1.053657     1.187970     1.415239     1.678291   
min      -3.340000    -3.250000    -4.200000    -3.840000    -3.480000   
25%      -0.680000    -0.372500    -0.150000    -0.020000     0.037500   
50%       0.010000     0.340000     0.660000     0.940000     1.120000   
75%       0.690000     1.050000     1.460000     1.970000     2.540000   
max       3.940000     3.880000     4.720000     5.750000     6.500000   

                5            6            7            8            9   ...  \
count  5000.000000  5000.000000  5000.000000  5000.000000  5000.000000  ...   
mean      1.997306     2.661806     2.659228     2.672086     2.988668  ...   
std       1.814187     2.015774     1.746067     1.663277     1.531506  ...   
min      -2.760000    -3.320000    -3.520000    -3.380000    -1.790000  ...   
25%       0.590000     1.110000     1.390000     1.470000     1.880000  ...   
50%       1.860000     2.500000     2.720000     2.810000     3.000000  ...   
75%       3.340000     4.210000     3.940000     3.940000     4.080000  ...   
max       7.620000     8.760000     7.840000     7.900000     7.630000  ...   

                11           12           13           14           15  \
count  5000.000000  5000.000000  5000.000000  5000.000000  5000.000000   
mean      3.013614     2.678908     2.648632     2.647668     2.000504   
std       1.512448     1.651588     1.760113     2.018768     1.810684   
min      -1.690000    -2.610000    -2.820000    -2.560000    -2.990000   
25%       1.920000     1.480000     1.360000     1.120000     0.640000   
50%       3.000000     2.830000     2.700000     2.490000     1.820000   
75%       4.082500     3.932500     3.980000     4.182500     3.330000   
max       7.400000     7.500000     7.750000     8.720000     7.860000   

                16           17           18           19           20  
count  5000.000000  5000.000000  5000.000000  5000.000000  5000.000000  
mean      1.335032     1.000622     0.661482     0.357300    -0.021378  
std       1.669949     1.412815     1.197326     1.081337     0.997064  
min      -3.560000    -4.080000    -3.500000    -3.570000    -3.880000  
25%       0.070000    -0.010000    -0.180000    -0.350000    -0.690000  
50%       1.200000     0.940000     0.620000     0.350000    -0.030000  
75%       2.532500     1.960000     1.470000     1.072500     0.660000  
max       6.740000     6.200000     5.280000     4.650000     4.010000  

[8 rows x 21 columns]

In [ ]:
x.columns

Int64Index([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
            19, 20],
           dtype='int64')

In [ ]:
from sklearn.preprocessing import MinMaxScaler
columns_to_scale=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18,19, 20]
scaler=MinMaxScaler()
df[columns_to_scale]=scaler.fit_transform(df[columns_to_scale])

In [ ]:
print(x)
x.describe()

            0         1         2         3         4         5         6   \
0     0.289835  0.237027  0.274664  0.371220  0.408818  0.479769  0.345199   
1     0.364011  0.796634  0.539238  0.617310  0.579158  0.578998  0.731788   
2     0.442308  0.323983  0.615471  0.670490  0.591182  0.607900  0.683775   
3     0.576923  0.496494  0.716368  0.398332  0.461924  0.507707  0.471026   
4     0.618132  0.507714  0.515695  0.338895  0.615230  0.362235  0.497517   
...        ...       ...       ...       ...       ...       ...       ...   
4995  0.369505  0.552595  0.727578  0.383733  0.399800  0.290944  0.468543   
4996  0.456044  0.549790  0.733184  0.732013  0.565130  0.725434  0.829470   
4997  0.460165  0.176718  0.488789  0.640250  0.295591  0.451830  0.573675   
4998  0.403846  0.513324  0.417040  0.508863  0.427856  0.202312  0.372517   
4999  0.545330  0.446003  0.774664  0.666319  0.685371  0.576108  0.580298   

            7         8         9   ...        11        12    

0            1            2            3            4   \
count  5000.000000  5000.000000  5000.000000  5000.000000  5000.000000   
mean      0.459498     0.503330     0.546237     0.503818     0.480049   
std       0.138754     0.147778     0.133180     0.147574     0.168165   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.365385     0.403576     0.454036     0.398332     0.352455   
50%       0.460165     0.503506     0.544843     0.498436     0.460922   
75%       0.553571     0.603086     0.634529     0.605839     0.603206   
max       1.000000     1.000000     1.000000     1.000000     1.000000   

                5            6            7            8            9   ...  \
count  5000.000000  5000.000000  5000.000000  5000.000000  5000.000000  ...   
mean      0.458315     0.495183     0.543946     0.536532     0.507290  ...   
std       0.174777     0.166869     0.153703     0.147454     0.162580  ...   
min       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
25%       0.322736     0.366722     0.432218     0.429965     0.389597  ...   
50%       0.445087     0.481788     0.549296     0.548759     0.508493  ...   
75%       0.587669     0.623344     0.656690     0.648936     0.623142  ...   
max       1.000000     1.000000     1.000000     1.000000     1.000000  ...   

                11           12           13           14           15  \
count  5000.000000  5000.000000  5000.000000  5000.000000  5000.000000   
mean      0.517449     0.523136     0.517373     0.461673     0.459954   
std       0.166386     0.163362     0.166520     0.178969     0.166883   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.397140     0.404550     0.395459     0.326241     0.334562   
50%       0.515952     0.538081     0.522233     0.447695     0.443318   
75%       0.635039     0.647132     0.643330     0.597739     0.582488   
max       1.000000     1.000000     1.000000     1.000000     1.000000   

                16           17           18           19           20  
count  5000.000000  5000.000000  5000.000000  5000.000000  5000.000000  
mean      0.475246     0.494224     0.473973     0.477774     0.489052  
std       0.162131     0.137433     0.136370     0.131549     0.126371  
min       0.000000     0.000000     0.000000     0.000000     0.000000  
25%       0.352427     0.395914     0.378132     0.391727     0.404309  
50%       0.462136     0.488327     0.469248     0.476886     0.487959  
75%       0.591505     0.587549     0.566059     0.564781     0.575412  
max       1.000000     1.000000     1.000000     1.000000     1.000000  

[8 rows x 21 columns]

In [ ]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x.values,y.values,random_state=42,test_size=0.2)

print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(4000, 21)
(4000,)
(1000, 21)
(1000,)


In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix,classification_report

In [ ]:
clf1=KNeighborsClassifier(n_neighbors=5,p=1)
clf2=KNeighborsClassifier(n_neighbors=10,p=2)

In [ ]:
clf1.fit(x_train,y_train)
clf2.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=10)

In [ ]:
pred1=clf1.predict(x_test)
pred2=clf2.predict(x_test)

In [ ]:
cm1=confusion_matrix(y_test,pred1)
cm2=confusion_matrix(y_test,pred2)

In [ ]:
print(cm1)

[[247  44  42]
 [ 19 312  23]
 [ 18  24 271]]


In [ ]:
print(cm2)

[[273  30  30]
 [ 32 304  18]
 [ 27  25 261]]


In [ ]:
cl1=classification_report(y_test,pred1)
cl2=classification_report(y_test,pred2)

In [ ]:
print(cl1)

              precision    recall  f1-score   support

           0       0.87      0.74      0.80       333
           1       0.82      0.88      0.85       354
           2       0.81      0.87      0.84       313

    accuracy                           0.83      1000
   macro avg       0.83      0.83      0.83      1000
weighted avg       0.83      0.83      0.83      1000



In [ ]:
print(cl2)

              precision    recall  f1-score   support

           0       0.82      0.82      0.82       333
           1       0.85      0.86      0.85       354
           2       0.84      0.83      0.84       313

    accuracy                           0.84      1000
   macro avg       0.84      0.84      0.84      1000
weighted avg       0.84      0.84      0.84      1000

